### ISSUE TITLE
release as a gem?

### ISSUE THREAD

**Issue by mooreniemi** [komputerwiz/csp-solver#3]
Would be nice if this lib followed standard Ruby convention and was installable as a gem. I'm happy to make a PR with that change if you're willing to release it on Rubygems.

I think a `spec/` or `test/` dir would be helpful too: one of my favorite ways to see how an API is used is to look at its tests. Likewise happy to provide one.

**Comment by komputerwiz** [comment]
Thanks for the suggestion, @mooreniemi! That sounds like it would be a good idea.

To be honest, I'm not really familiar with how Ruby applications and libraries should be structured. Most of the Ruby things I've done have been short(-ish) scripts to quickly solve a problem, and `csp-solver` seemed like it would be worth sharing. In some of my more complex scripts, I've used the Rails project layout as a template just to give some structure, but this doesn't feel right for general-purpose libraries. I really need to do some Googling on the subject. Do you have any recommended readings?

To the matter at hand, it sounds like you have much more experience in this area: if you wouldn't mind implementing these (time permitting, of course; no rush) and sending me a PR, I'd be happy to accept it. It'll be a good learning experience for me.

In the meantime, I'll start reading up on how to submit a gem to Rubygems.

Thanks again!

**Comment by mooreniemi** [comment]
@komputerwiz I'd be happy to, actually! I will submit a PR relatively-soonish I think. :)

**Comment by komputerwiz** [comment]
I've just pushed the gem to rubygems.org: https://rubygems.org/gems/csp-solver

Thanks again for the help!
